name: Docker Build

on:
  push:
    branches: ['main']
    paths: ['papka/push_here_pls/**']


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build Docker image
      env:
        GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
      run: |
        docker build --build-arg GITHUB_TOKEN=$GITHUB_TOKEN -t my-docker-image ./papka

    - name: Save emir.txt
      run: |
        docker run --rm -v $(pwd):/output my-docker-image cp /emir.txt /output/emir.txt

    - name: Upload emir.txt
      uses: actions/upload-artifact@v2
      with:
        name: emir-text-file
        path: emir.txt
